# Generated by Django 2.0.2 on 2018-04-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoiveRe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('imgurl', models.TextField(max_length=200)),
                ('summary', models.TextField(max_length=200)),
            ],
        ),
    ]
