# Generated by Django 2.0.2 on 2018-04-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoiveRe', '0004_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRatingAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'movie_rating_avg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieRatingTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('rating_times', models.BigIntegerField()),
            ],
            options={
                'db_table': 'movie_rating_times',
                'managed': False,
            },
        ),
    ]
