# Generated by Django 2.0.2 on 2018-04-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoiveRe', '0006_auto_20180426_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_created=True)),
                ('rating_est', models.DecimalField(decimal_places=4, max_digits=14)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoiveRe.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoiveRe.MovielensUser')),
            ],
        ),
    ]
